### ISSUE TITLE
Import old blogger information from old planetxamarin?

### ISSUE THREAD

**Issue by ghuntley** [ghuntley/planetxamarin#21]
> I have all of the older blogger information that I can import from the old planet xamarin.

I'm not a fan of automatically importing old blogger information, we should instead contact developers individually via private email and see if they are still active/interested in producing content. If they are, get them to submit a pull-request. That way if there are ever problems and we need to disable an authors feed it's super obvious of the username we should be nerd sniping on GitHub. It also encourages the author to get involved with open-source.

**Comment by jamesmontemagno** [comment]
That sounds good :)
