### ISSUE TITLE
Move Repo to "PlanetXamarin" Organization

### ISSUE THREAD

**Issue by jamesmontemagno** [ghuntley/planetxamarin#23]
Want to get some feedback, but I am thinking we should create a PlanetXamarin organization for whomever needs admin writes on it for deploy and such.

**Comment by ghuntley** [comment]
👍 on this, removes dependency on me when adding/removing contributors or reconfiguring hooks.

**Comment by ghuntley** [comment]
The repo has been moved to an org and teams created. Check your inbox for invitations.

![image](https://cloud.githubusercontent.com/assets/127353/21973651/5017c9c6-dc16-11e6-8393-f5a038c14d49.png)

![image](https://cloud.githubusercontent.com/assets/127353/21973664/5d583774-dc16-11e6-9d10-44f5e947d82c.png)
